#pragma once

namespace Plaza {
	enum PlazaTextureType {
		PL_TYPE_1D = 0,
		PL_TYPE_2D,
		PL_TYPE_3D,
	};

	enum PlazaViewType {
		PL_VIEW_TYPE_1D = 0,
		PL_VIEW_TYPE_2D = 1,
		PL_VIEW_TYPE_3D = 2,
		PL_VIEW_TYPE_CUBE = 3,
		PL_VIEW_TYPE_1D_ARRAY = 4,
		PL_VIEW_TYPE_2D_ARRAY = 5,
		PL_VIEW_TYPE_CUBE_ARRAY = 6
	};

	enum PlazaBufferType {
		PL_BUFFER_PUSH_CONSTANTS = 0,
		PL_BUFFER_UNIFORM_BUFFER,
		PL_BUFFER_STORAGE_BUFFER,
		PL_BUFFER_STORAGE_BUFFER_DYNAMIC,
		PL_BUFFER_SAMPLER,
		PL_BUFFER_COMBINED_IMAGE_SAMPLER
	};

	enum PlazaTextureFormat {
		PL_FORMAT_R32G32B32A32_SFLOAT = 0,
		PL_FORMAT_R32G32B32_SFLOAT,
		PL_FORMAT_R8G8B8A8_UNORM,
		PL_FORMAT_R8G8B8_UNORM,
		PL_FORMAT_D32_SFLOAT_S8_UINT
	};

	enum PlazaImageUsage {
		PL_IMAGE_USAGE_TRANSFER_SRC = 1 << 0,
		PL_IMAGE_USAGE_TRANSFER_DST = 1 << 1,
		PL_IMAGE_USAGE_SAMPLED = 1 << 2,
		PL_IMAGE_USAGE_STORAGE = 1 << 3,
		PL_IMAGE_USAGE_COLOR_ATTACHMENT = 1 << 4,
		PL_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT = 1 << 5,
		PL_IMAGE_USAGE_INPUT_ATTACHMENT = 1 << 6,
	};

	enum PlazaImageLayout {
		PL_IMAGE_LAYOUT_UNDEFINED = 0,
		PL_IMAGE_LAYOUT_GENERAL = 1,
		PL_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL = 2,
		PL_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL = 3,
		PL_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL = 4,
		PL_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL = 5,
		PL_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL = 6,
		PL_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL = 7,
		PL_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL = 8,
		PL_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL = 9,
		PL_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL = 10,
		PL_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL = 11,
		PL_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL = 12,
		PL_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL = 13,
		PL_IMAGE_LAYOUT_READ_ONLY_OPTIMAL = 14,
		PL_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL = 15,
		PL_IMAGE_LAYOUT_PRESENT_SRC_KHR = 16,
		PL_IMAGE_LAYOUT_VIDEO_DECODE_DST_KHR = 17,
		PL_IMAGE_LAYOUT_VIDEO_DECODE_SRC_KHR = 18,
		PL_IMAGE_LAYOUT_VIDEO_DECODE_DPB_KHR = 19,
		PL_IMAGE_LAYOUT_SHARED_PRESENT_KHR = 20,
		PL_IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT = 21,
		PL_IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR = 22,
	};

	enum PlazaRenderStage {
		PL_STAGE_VERTEX = 1 << 0,
		PL_STAGE_FRAGMENT = 1 << 1,
		PL_STAGE_COMPUTE = 1 << 2,
		PL_STAGE_ALL = 1 << 3,
	};

	enum PlazaBindingType {
		PL_BINDING_UNDEFINED = 1 << 0,
		PL_BINDING_BUFFER = 1 << 1,
		PL_BINDING_TEXTURE = 1 << 2
	};

	enum PlazaMemoryProperty : uint32_t {
		PL_MEMORY_PROPERTY_DEVICE_LOCAL = 1 << 0,
		PL_MEMORY_PROPERTY_HOST_VISIBLE = 1 << 1,
		PL_MEMORY_PROPERTY_HOST_COHERENT = 1 << 2,
		PL_MEMORY_PROPERTY_HOST_CACHED = 1 << 3,
		PL_MEMORY_PROPERTY_LAZILY_ALLOCATED = 1 << 4,
		PL_MEMORY_PROPERTY_PROTECTED = 1 << 5
	};

	enum PlazaBufferUsage : uint32_t {
		PL_BUFFER_USAGE_TRANSFER_SRC = 1 << 0,
		PL_BUFFER_USAGE_TRANSFER_DST = 1 << 1,
		PL_BUFFER_USAGE_UNIFORM_BUFFER = 1 << 2,
		PL_BUFFER_USAGE_STORAGE_BUFFER = 1 << 3,
		PL_BUFFER_USAGE_INDEX_BUFFER = 1 << 4,
		PL_BUFFER_USAGE_VERTEX_BUFFER = 1 << 5,
		PL_BUFFER_USAGE_INDIRECT_BUFFER = 1 << 6,
	};

	enum PlazaMemoryUsage {
		PL_MEMORY_USAGE_UNKNOWN = 0,
		PL_MEMORY_USAGE_GPU_ONLY = 1,
		PL_MEMORY_USAGE_CPU_ONLY = 2,
		PL_MEMORY_USAGE_CPU_TO_GPU = 3,
		PL_MEMORY_USAGE_GPU_TO_CPU = 4,
		PL_MEMORY_USAGE_CPU_COPY = 5,
		PL_MEMORY_USAGE_GPU_LAZILY_ALLOCATED = 6,
		PL_MEMORY_USAGE_AUTO = 7,
		PL_MEMORY_USAGE_AUTO_PREFER_DEVICE = 8,
		PL_MEMORY_USAGE_AUTO_PREFER_HOST = 9,
	};
}